# Generated by Django 5.1.6 on 2025-04-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('wave_height', models.FloatField(help_text='Wave height in meters')),
                ('wind_speed', models.FloatField(help_text='Wind speed in knots')),
                ('wind_direction', models.FloatField(help_text='Wind direction in degrees')),
                ('current_speed', models.FloatField(help_text='Current speed in knots')),
                ('current_direction', models.FloatField(help_text='Current direction in degrees')),
                ('visibility', models.FloatField(help_text='Visibility in nautical miles')),
                ('precipitation', models.FloatField(help_text='Precipitation in mm/hour')),
                ('topsis_score', models.FloatField(help_text='Combined score for navigation (lower is better)')),
                ('is_water', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['row', 'col'], name='routing_gri_row_2e8a95_idx'), models.Index(fields=['is_water'], name='routing_gri_is_wate_dd75a6_idx')],
                'unique_together': {('row', 'col')},
            },
        ),
    ]
