# Generated by Django 5.1.6 on 2025-04-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
